// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://izvqijnaakgdmbaidozk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dnFpam5hYWtnZG1iYWlkb3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzEyNjIsImV4cCI6MjA2NDUwNzI2Mn0.SDi8uJLj-073Ulc9cXSMCU3-8JxZ87VooSHtKVkADzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);

// src/integrations/supabase/client.ts
export async function getStudentSkills(userId: string): Promise<string[]> {
  const { data, error } = await supabase
    .from("student_profiles")
    .select("skills")
    .eq("user_id", userId)
    .single();

  if (error) {
    console.error("Error fetching skills:", error.message);
    return [];
  }

  // Cast Json → string[]; fallback to empty array if undefined
  return (data?.skills as unknown as string[]) ?? [];
}

// src/integrations/supabase/client.ts

// ① Remove `type` from your Job interface
export interface Job {
    id: string
    title: string
    company: string
    requirements: string[]
    location: string          // this one exists
    salary_range: string | null  // if you want to display “Full-time”, etc.
  }
  
  // ② In getActiveJobs(), select only real columns
  export async function getActiveJobs(): Promise<Job[]> {
    const { data, error } = await supabase
      .from('job_postings')
      .select('id, title, company, requirements, location, salary_range')
      .eq('is_active', true);
  
    if (error) {
      console.error('Error fetching jobs:', error.message);
      return [];
    }
  
    // data is Job[] | null
    const jobs = data ?? [];
  
    // ③ Cast requirements from Json → string[]
    return jobs.map((job) => ({
      ...job,
      requirements: job.requirements as unknown as string[],
    }));
  }
  